### ISSUE TITLE
contributing.md missing

### ISSUE THREAD

**Issue by hrittikhere** [Ananya-0306/Cybersecurity#1]
**Describe the bug**
The contributing.md file mentioned in the readme.md is missing 

**Expected behaviour**
If clicked on the contributing.md guidelines should appear

**Additional context**
Readme.md: https://github.com/Ananya-0306/Cybersecurity/blob/main/README.md
![image](https://user-images.githubusercontent.com/67012359/115104854-de55f800-9f78-11eb-801e-9b479d39dbbf.png)

**Comment by Ananya-0306** [comment]
Hi Hritik Roy, Thankyou for updating, now i added the file please have a
look https://github.com/Ananya-0306/Cybersecurity/blob/main/CONTRIBUTING.md
